# === Font and Appearance ===
font_family Iosevka Term Extended
font_size 13.0
bold_font Iosevka Term Bold Extended
italic_font Iosevka Term Extended Italic

cursor_shape block
cursor_blink_interval 0.8

allow_remote_control yes

background_opacity 0.90

# === Clipboard ===
# Copy with Ctrl+Shift+C (default)
# Paste with Ctrl+V (custom)
map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# === Tab Management ===
# Open new tab: Ctrl+Shift+T
map ctrl+t new_tab_with_cwd

# Close current tab: Ctrl+Shift+W
#map ctrl+w close_tab

# Next tab: Ctrl+Shift+Right
map ctrl+right next_tab

# Previous tab: Ctrl+Shift+Left
map ctrl+left previous_tab

# === Dummy Keybindings (for example) ===
# Ctrl+Shift+Y: noop (disabled)
map ctrl+shift+y noop

# === Reload Config ===
map ctrl+r reload_config

# === Fullscreen toggle ===
map ctrl+shift+f toggle_fullscreen

initial_window_width  110c
initial_window_height 35c

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

remember_window_size no
# active_border_color   #ff79c6    
# inactive_border_color #131317

window_border_width   1

tab_bar_style powerline
tab_powerline_style slanted
tab_separator " | "
tab_title_template "{index} {title}"
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0


# Colors
# tab_bar_background        #1e1e2e
# active_tab_foreground     #ffffff
# active_tab_background     #9e60a6   
# inactive_tab_foreground   #888888
# inactive_tab_background   #1e1e2e

# Smooth scrolling settings
scrollback_lines 2000
wheel_scroll_min_lines 1

# Custom color scheme
# foreground #d1d1d8
# background #121216
# cursor     #ffffff
# color0     #1a1a1f
# color1     #985863
# color2     #58986b
# color3     #989858
# color4     #585f98
# color5     #985898
# color6     #676798
# color7     #a1a1a8
# color8     #3d3d45
# color9     #b86d7e
# color10    #6db881
# color11    #b8b86d
# color12    #6d74b8
# color13    #b86db8
# color14    #7e7eb8
# color15    #e2e2e8

include monochrome.conf
