selection_foreground #000000
selection_background #ffffff

foreground #ffffff
background #000000

# Black / Grey
color0   #000000
color8   #333333

# Red (swapped from color2)
color1   #dd9999
color9   #dd9999

# Green (swapped from color1)
color2   #5f8787
color10  #5f8787

# Yellow (now an ashen white shade)
color3   #d1d1d1
color11  #e2e2e2

# Blue / Purple / Cyan (Grayscale/Metal tones)
color4   #888888
color12  #888888
color5   #999999
color13  #999999
color6   #aaaaaa
color14  #aaaaaa

# White
color7   #c1c1c1
color15  #c1c1c1

active_tab_foreground #ffffff
active_tab_background #000000
inactive_tab_foreground #666666
inactive_tab_background #000000

active_border_color #ffffff
cursor #ffffff
